# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0003_auto_20160612_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='_loginuser_friends_+', to='chatroom.LoginUser'),
        ),
    ]
