"""
Django settings for afcat project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ly(u=4wvcol=1o^jff3@txewr88q5!humdtp=)c_6y26w(*8fs'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'guardian',
    'afcat.cmdb',
    'afcat.tracker',
    'afcat.account',
    'afcat.monitor'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'account.core.privatemiddle.PromissionMiddle',
]

ROOT_URLCONF = 'afcat.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'afcat.api.libs.menu.common_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'afcat.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': "zabbix",
#         'HOST': '127.0.0.1',
#         'USER': 'root',
#         'PASSWORD': '123456',
#         'PORT': '3306',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': "zabbix",
        'HOST': '127.0.0.1',
        'USER': 'weiboy',
        'PASSWORD': '123456',
        'PORT': '3306',
    },
    'cmdb': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': "taiyuan-cmdb",
        'HOST': '127.0.0.1',
        'USER': 'weiboy',
        'PASSWORD': '123456',
        'PORT': '3306',
    }
}

DATABASE_ROUTERS = ['afcat.database_router.DatabaseAppsRouter']
DATABASE_APPS_MAPPING = {
    # example:
    #'app_name':'database_name',
    'guardian': 'cmdb',
    'account': 'cmdb',
    'cmdb': 'cmdb',
    'admin': 'cmdb',
    'auth':  'cmdb',
    'contenttypes': 'cmdb',
    'sessions': 'cmdb',
}

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# configuration for guardian
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend', # this is default
    'guardian.backends.ObjectPermissionBackend',
)
# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format':
                '%(levelname)s\t'
                '%(method)5s\t'
                '%(asctime)s\t'
                '[%(modules)-25s]\t'
                '[%(error_line)7s]\t'
                '%(user)-10s '
                '[%(remote_user_ip)15s]\t'
                '[%(url)s]\t'
                '[%(message)s]\t'
                '[%(remote_user_agent)s]\t'
        },
        'simple': {
            'format': '%(levelname)s\t%(asctime)s\t%(filename)s\t%(lineno)d'
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/access.log'),
            'formatter': 'verbose',
            'maxBytes': 1024*1024*10,
            'backupCount': 5,
        },
        'console': {
            'class': 'logging.StreamHandler',
            'level': 'INFO',
            'formatter': 'verbose'
        },
    },
    'loggers': {
        'api': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
            'formatter': 'verbose'
        },
        'monitor': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
            'formatter': 'verbose'
        },
        'tracker': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
            'formatter': 'verbose'
        },
        'cmdb': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
            'formatter': 'verbose'
        },
    'afcat': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
            'formatter': 'verbose'
        }
    },
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# 监控服务器IP
MONITOR_SERVER = '192.168.111.249'

FIXTURE_DIRS = [
    os.path.join(BASE_DIR, "fixtures"),
]

# session config
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 60000

handler400 = 'afcat.api.views.bad_request_view'
handler403 = 'afcat.api.views.permission_denied_view'
handler404 = "afcat.api.views.page_not_found_view"
handler500 = 'afcat.api.views.error_view'
