# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='head_img',
            field=models.CharField(default='head-1.png', max_length=30, verbose_name='头像'),
        ),
    ]
