# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0004_auto_20160612_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='head_img',
            field=models.CharField(choices=[('head-1.png', '男士1'), ('head-3.png', '男士2'), ('head-4.png', '男士3'), ('head-2.png', '女士1'), ('head-5.png', '女士2'), ('head-6.png', '女士3')], default='head-1.png', max_length=30, verbose_name='头像'),
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='members',
        ),
        migrations.AddField(
            model_name='usergroup',
            name='members',
            field=models.ManyToManyField(related_name='usergroup_member', to='chatroom.LoginUser'),
        ),
    ]
