# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0005_auto_20160612_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='isdefault',
            field=models.IntegerField(default=0),
        ),
    ]
