# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-15 11:02
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='equipment',
            managers=[
                ('report', django.db.models.manager.Manager()),
            ],
        ),
    ]
