# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-15 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20161215_1443'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='assets',
            managers=[
            ],
        ),
    ]
