# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-16 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_auto_20161215_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assets',
            options={'ordering': ['-createdate'], 'permissions': (('view_assets', 'Can View Assets'),), 'verbose_name': '服务器资产', 'verbose_name_plural': '服务器资产'},
        ),
        migrations.AlterModelOptions(
            name='backuprecord',
            options={'ordering': ['-backupdate'], 'verbose_name': '数据备份', 'verbose_name_plural': '数据备份'},
        ),
        migrations.AlterModelOptions(
            name='cpumemory',
            options={'verbose_name': 'CPU内存', 'verbose_name_plural': 'CPU内存'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['-createdate'], 'permissions': (('view_equipment', 'Can View Equipment'),), 'verbose_name': '网络设备', 'verbose_name_plural': '网络设备'},
        ),
        migrations.AlterModelOptions(
            name='equipmentboardcard',
            options={'verbose_name': '网络设备板卡', 'verbose_name_plural': '网络设备板卡'},
        ),
        migrations.AlterModelOptions(
            name='installedsoftlist',
            options={'verbose_name': '安装软件', 'verbose_name_plural': '安装软件'},
        ),
        migrations.AlterModelOptions(
            name='ipallocation',
            options={'permissions': (('view_ipallocation', 'Can View IPAllocation'),), 'verbose_name': 'IP分配', 'verbose_name_plural': 'IP分配'},
        ),
        migrations.AlterModelOptions(
            name='ipconfiguration',
            options={'verbose_name': '主机IP配置', 'verbose_name_plural': '主机IP配置'},
        ),
        migrations.AlterModelOptions(
            name='ipsource',
            options={'permissions': (('view_ipsource', 'Can View IPSource'),), 'verbose_name': 'IP资源', 'verbose_name_plural': 'IP资源'},
        ),
        migrations.AlterModelOptions(
            name='portlist',
            options={'verbose_name': '端口列表', 'verbose_name_plural': '端口列表'},
        ),
        migrations.AlterModelOptions(
            name='portmapping',
            options={'verbose_name': '端口映射', 'verbose_name_plural': '端口映射'},
        ),
        migrations.AlterModelOptions(
            name='r_equipment_staff',
            options={'verbose_name': '网络设备联系人', 'verbose_name_plural': '网络设备联系人'},
        ),
        migrations.AlterModelOptions(
            name='r_server_business',
            options={'verbose_name': '主机业务', 'verbose_name_plural': '主机业务'},
        ),
        migrations.AlterModelOptions(
            name='r_server_staff',
            options={'verbose_name': '主机联系人', 'verbose_name_plural': '主机联系人'},
        ),
        migrations.AlterModelOptions(
            name='serverboardcard',
            options={'verbose_name': '主机板卡', 'verbose_name_plural': '主机板卡'},
        ),
        migrations.AlterModelOptions(
            name='servers',
            options={'ordering': ['-createdate'], 'permissions': (('view_servers', 'Can View Servers'),), 'verbose_name': '主机', 'verbose_name_plural': '主机'},
        ),
        migrations.AlterModelOptions(
            name='storagelv',
            options={'verbose_name': '存储LV', 'verbose_name_plural': '存储LV'},
        ),
        migrations.AlterModelOptions(
            name='storagepv',
            options={'verbose_name': '存储PV', 'verbose_name_plural': '存储PV'},
        ),
        migrations.AlterModelOptions(
            name='storagevg',
            options={'verbose_name': '主机存储', 'verbose_name_plural': '主机存储'},
        ),
    ]
