# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-17 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_auto_20161216_1249'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='operateaudit',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='operateaudit',
            old_name='modelname',
            new_name='model_name',
        ),
        migrations.RenameField(
            model_name='operateaudit',
            old_name='operatedata',
            new_name='operate_data',
        ),
        migrations.RemoveField(
            model_name='operateaudit',
            name='operatetime',
        ),
        migrations.AddField(
            model_name='operateaudit',
            name='object_pk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='operateaudit',
            name='operate_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='操作时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operateaudit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
