# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-17 23:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0007_auto_20161217_2331'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='operateaudit',
            managers=[
            ],
        ),
    ]
