# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-22 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0009_auto_20161221_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ids',
            name='tablename',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='ids',
            unique_together=set([('tablename', 'nextid')]),
        ),
    ]
