# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-22 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0013_auto_20161222_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecustomerinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
