# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-22 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0015_auto_20161222_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecustomerinfo',
            name='delstatus',
            field=models.IntegerField(default=0, verbose_name='删除状态'),
        ),
        migrations.AlterField(
            model_name='basecustomerinfo',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
