# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-22 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0016_auto_20161222_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basecustomerinfo',
            name='delstatus',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='cust',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cust_equipment', to='cmdb.BaseCustomerInfo', to_field='idcode'),
        ),
        migrations.AlterField(
            model_name='itemsset',
            name='cust',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.BaseCustomerInfo', to_field='idcode', verbose_name='所属客户'),
        ),
        migrations.AlterField(
            model_name='servers',
            name='cust',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cust_server', to='cmdb.BaseCustomerInfo', to_field='idcode'),
        ),
    ]
