# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-26 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0017_auto_20161222_1637'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ids',
            unique_together=set([]),
        ),
    ]
