# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-29 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0020_auto_20161227_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipsource',
            options={'permissions': (('view_ipsource', 'Can View IPSource'),), 'verbose_name': 'IP地址资源', 'verbose_name_plural': 'IP地址资源'},
        ),
        migrations.AlterField(
            model_name='assets',
            name='assetstatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_status', to='cmdb.BaseAssetStatus', verbose_name='设备状态'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='cpu',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CPU'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='cust',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_cust', to='cmdb.BaseCustomerInfo', to_field='idcode', verbose_name='所属客户'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='sn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='序列号(SN)'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='unitinfo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='单元信息'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='updateuser',
            field=models.CharField(max_length=100, null=True, verbose_name='最近更新人'),
        ),
        migrations.AlterField(
            model_name='baseassetstatus',
            name='flag',
            field=models.IntegerField(default=0, verbose_name='销毁标识'),
        ),
        migrations.AlterField(
            model_name='baseassettype',
            name='flag',
            field=models.IntegerField(choices=[(1, '是'), (0, '否')], default=0, verbose_name='是否虚机类型'),
        ),
        migrations.AlterField(
            model_name='basebalancetype',
            name='typename',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='F5策略'),
        ),
        migrations.AlterField(
            model_name='basecustomerinfo',
            name='custCode',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='客户编号'),
        ),
        migrations.AlterField(
            model_name='basecustomerinfo',
            name='custname',
            field=models.CharField(max_length=200, verbose_name='客户名称'),
        ),
        migrations.AlterField(
            model_name='baseequipmenttype',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='类型名称'),
        ),
        migrations.AlterField(
            model_name='basefactory',
            name='name',
            field=models.CharField(max_length=200, verbose_name='厂商名称'),
        ),
        migrations.AlterField(
            model_name='basenetarea',
            name='name',
            field=models.CharField(max_length=100, verbose_name='网络区域名称'),
        ),
        migrations.AlterField(
            model_name='baseraidtype',
            name='typename',
            field=models.CharField(max_length=50, verbose_name='RAID类型'),
        ),
        migrations.AlterField(
            model_name='baserunningstatus',
            name='status',
            field=models.CharField(max_length=100, verbose_name='运行状态'),
        ),
        migrations.AlterField(
            model_name='basesoft',
            name='version',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='软件版本'),
        ),
        migrations.AlterField(
            model_name='cpumemory',
            name='corecount',
            field=models.CharField(max_length=10, null=True, verbose_name='CPU核数'),
        ),
        migrations.AlterField(
            model_name='cpumemory',
            name='cpucount',
            field=models.CharField(max_length=10, null=True, verbose_name='CPU数'),
        ),
        migrations.AlterField(
            model_name='cpumemory',
            name='frequency',
            field=models.CharField(max_length=50, null=True, verbose_name='频率'),
        ),
        migrations.AlterField(
            model_name='cpumemory',
            name='memory',
            field=models.IntegerField(null=True, verbose_name='内存'),
        ),
        migrations.AlterField(
            model_name='cpumemory',
            name='model',
            field=models.CharField(max_length=50, null=True, verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='cpumemory',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_cpu', to='cmdb.Servers', verbose_name='所属主机'),
        ),
        migrations.AlterField(
            model_name='ipallocation',
            name='ipcount',
            field=models.IntegerField(verbose_name='分配数'),
        ),
        migrations.AlterField(
            model_name='ipallocation',
            name='iplist',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='IP列表'),
        ),
        migrations.AlterField(
            model_name='ipallocation',
            name='ipsoure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation', to='cmdb.IPSource', verbose_name='所属IP资源'),
        ),
        migrations.AlterField(
            model_name='ipallocation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation', to='cmdb.Projects', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='ipallocation',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='ipsource',
            name='counts',
            field=models.IntegerField(verbose_name='地址数量'),
        ),
        migrations.AlterField(
            model_name='ipsource',
            name='endip',
            field=models.GenericIPAddressField(verbose_name='结束IP地址'),
        ),
        migrations.AlterField(
            model_name='ipsource',
            name='gatway',
            field=models.GenericIPAddressField(verbose_name='网关地址'),
        ),
        migrations.AlterField(
            model_name='ipsource',
            name='netarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.BaseNetArea', verbose_name='所属网络区域'),
        ),
        migrations.AlterField(
            model_name='ipsource',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='ipsource',
            name='startip',
            field=models.GenericIPAddressField(verbose_name='起始IP地址'),
        ),
        migrations.AlterField(
            model_name='ipsource',
            name='usedcount',
            field=models.IntegerField(default=0, verbose_name='已使用数量'),
        ),
        migrations.AlterField(
            model_name='r_machineroom_staff',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='r_machineroom_staff',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.BaseRole', verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='r_machineroom_staff',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_staffs', to='cmdb.BaseMachineRoom', verbose_name='机房'),
        ),
        migrations.AlterField(
            model_name='r_machineroom_staff',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Staffs', verbose_name='联系人'),
        ),
        migrations.AlterField(
            model_name='serverboardcard',
            name='cardtype',
            field=models.IntegerField(choices=[(1, '网卡'), (2, '存储卡')], default=1, verbose_name='卡类型'),
        ),
        migrations.AlterField(
            model_name='serverboardcard',
            name='sn',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='设备编号(SN)'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_staffs', to='cmdb.BaseCompany', verbose_name='所属公司'),
        ),
    ]
