# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-17 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0023_auto_20170117_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPManage',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ipaddr', models.GenericIPAddressField(verbose_name='IP地址')),
                ('status', models.TextField(choices=[('1', '已预留'), ('2', '已分配'), ('3', '已使用'), ('4', '待回收')], max_length=5, verbose_name='IP状态')),
                ('allocateuser', models.TextField(blank=True, max_length=20, null=True, verbose_name='分配人')),
                ('allocatedate', models.DateField(auto_now_add=True, verbose_name='分配日期')),
                ('allocateto', models.TextField(blank=True, max_length=200, null=True, verbose_name='分配系统或设备')),
                ('binded', models.TextField(blank=True, max_length=200, null=True, verbose_name='绑定设备')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('ipmask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.IPDesign', verbose_name='IP地址段')),
            ],
            options={
                'verbose_name': 'IP分配',
                'verbose_name_plural': 'IP分配',
                'permissions': (('view_ipallocation', 'Can View IPAllocation'),),
            },
        ),
    ]
