# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-17 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0024_ipmanage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdesign',
            name='cust',
            field=models.ForeignKey(default=1001, on_delete=django.db.models.deletion.CASCADE, to_field='idcode', to='cmdb.BaseCustomerInfo', verbose_name='所属客户'),
            preserve_default=False,
        ),
    ]
