# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-17 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0025_ipdesign_cust'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdesign',
            name='cust',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.BaseCustomerInfo', to_field='idcode', verbose_name='所属客户'),
        ),
    ]
