# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-19 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0026_auto_20170117_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['project', 'bussname'], 'permissions': (('view_business', 'Can View Business'),), 'verbose_name': '业务模块', 'verbose_name_plural': '业务模块'},
        ),
        migrations.AlterField(
            model_name='ipdesign',
            name='parentip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submask', to='cmdb.IPDesign', verbose_name='子网归属'),
        ),
        migrations.AlterField(
            model_name='ipmanage',
            name='ipmask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocated', to='cmdb.IPDesign', verbose_name='IP地址段'),
        ),
    ]
