# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-03 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0028_auto_20170203_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdesign',
            name='usefor',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='用途'),
        ),
        migrations.AddField(
            model_name='ipdesign',
            name='vlan',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='VLAN范围'),
        ),
    ]
