# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-04 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0029_auto_20170203_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipmanage',
            name='vlan',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='VLAN编号'),
        ),
    ]
