# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-04 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0030_ipmanage_vlan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipmanage',
            options={'permissions': (('view_ipallocation', 'Can View IPAllocation'),), 'verbose_name': 'IP分配管理', 'verbose_name_plural': 'IP分配管理'},
        ),
    ]
