# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-06 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0031_auto_20170204_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipmanage',
            name='cust',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.BaseCustomerInfo', to_field='idcode', verbose_name='所属客户'),
        ),
    ]
