# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-08 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0033_balancemapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancemapping',
            name='ploy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.BaseBalanceType', verbose_name='策略'),
        ),
    ]
