# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-08 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0034_balancemapping_ploy'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancemapping',
            name='hosttype',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='主机类型'),
        ),
    ]
