# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-10 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0035_balancemapping_hosttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancemapping',
            name='datacenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.BaseDataCenter', verbose_name='数据中心'),
        ),
    ]
