# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-13 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0036_balancemapping_datacenter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balancemapping',
            options={'ordering': ['-createdate'], 'permissions': (('view_balancemapping', 'can view F5 Mapping'),), 'verbose_name': 'F5映射', 'verbose_name_plural': 'F5映射'},
        ),
        migrations.AddField(
            model_name='balancemapping',
            name='createdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
