# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-15 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0037_auto_20170213_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancemapping',
            name='vlan',
            field=models.TextField(blank=True, null=True, verbose_name='VLAN'),
        ),
    ]
