# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-10 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0038_auto_20170215_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='operateaudit',
            name='cust',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.BaseCustomerInfo', to_field='idcode'),
        ),
    ]
