# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-13 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0039_operateaudit_cust'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTableProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertykey', models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义key')),
                ('propertyname', models.CharField(blank=True, max_length=255, null=True, verbose_name='显示名称')),
                ('tablename', models.CharField(blank=True, max_length=255, null=True, verbose_name='表名称')),
                ('tablefield', models.CharField(blank=True, max_length=255, null=True, verbose_name='扩展字段名称')),
                ('createtime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('cust', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cust_field_customer', to='cmdb.BaseCustomerInfo', to_field='idcode', verbose_name='所属客户')),
            ],
            options={
                'verbose_name': '扩展字段表',
                'verbose_name_plural': '扩展字段表',
            },
        ),
        migrations.CreateModel(
            name='TableFieldPropertyClassify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertykey', models.CharField(blank=True, max_length=255, null=True, verbose_name='属性key')),
                ('propertyname', models.CharField(blank=True, max_length=255, null=True, verbose_name='显示名称')),
                ('tablename', models.CharField(blank=True, max_length=255, null=True, verbose_name='表名称')),
                ('tablefield', models.CharField(blank=True, max_length=255, null=True, verbose_name='字段名称')),
                ('createtime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('cust', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cust_field_alias', to='cmdb.BaseCustomerInfo', to_field='idcode', verbose_name='所属客户')),
            ],
            options={
                'verbose_name': '表字段别名',
                'verbose_name_plural': '表字段别名',
            },
        ),
        migrations.AlterField(
            model_name='equipment',
            name='assetname',
            field=models.CharField(max_length=200, null=True, verbose_name='设备名称'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='assetno',
            field=models.CharField(max_length=100, verbose_name='资产编号'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='assettype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assettype_equipment', to='cmdb.BaseEquipmentType', verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='createdate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='createuser',
            field=models.CharField(max_length=100, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='cust',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cust_equipment', to='cmdb.BaseCustomerInfo', to_field='idcode', verbose_name='所属客户'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='expiredate',
            field=models.DateField(null=True, verbose_name='过保日期'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='factory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.BaseFactory', verbose_name='厂商'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='manageip',
            field=models.GenericIPAddressField(null=True, verbose_name='管理IP'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model',
            field=models.CharField(max_length=100, null=True, verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='netarea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.BaseNetArea', verbose_name='网络区域'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='portcount',
            field=models.IntegerField(null=True, verbose_name='端口数'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='remark',
            field=models.CharField(max_length=300, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_equipment', to='cmdb.BaseMachineRoom', verbose_name='机房'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='slotindex',
            field=models.CharField(max_length=100, null=True, verbose_name='U位'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='sn',
            field=models.CharField(max_length=100, null=True, verbose_name='序列号'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.BaseAssetStatus', verbose_name='设备状态'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='tradedate',
            field=models.DateField(null=True, verbose_name='购买日期'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='updatedate',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日期'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='updateuser',
            field=models.CharField(max_length=100, verbose_name='更新人'),
        ),
    ]
