# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-14 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0041_auto_20170313_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancemapping',
            name='customer001',
        ),
        migrations.RemoveField(
            model_name='balancemapping',
            name='customer002',
        ),
        migrations.RemoveField(
            model_name='balancemapping',
            name='customer003',
        ),
        migrations.RemoveField(
            model_name='balancemapping',
            name='customer004',
        ),
        migrations.RemoveField(
            model_name='balancemapping',
            name='customer005',
        ),
        migrations.RemoveField(
            model_name='balancemapping',
            name='customer006',
        ),
        migrations.RemoveField(
            model_name='balancemapping',
            name='customer007',
        ),
        migrations.RemoveField(
            model_name='balancemapping',
            name='customer008',
        ),
        migrations.RemoveField(
            model_name='balancemapping',
            name='customer009',
        ),
        migrations.RemoveField(
            model_name='balancemapping',
            name='customer010',
        ),
        migrations.RemoveField(
            model_name='balancemapping',
            name='customer011',
        ),
        migrations.RemoveField(
            model_name='balancemapping',
            name='customer012',
        ),
        migrations.RemoveField(
            model_name='balancemapping',
            name='customer013',
        ),
        migrations.RemoveField(
            model_name='balancemapping',
            name='customer014',
        ),
        migrations.RemoveField(
            model_name='balancemapping',
            name='customer015',
        ),
        migrations.RemoveField(
            model_name='balancemapping',
            name='customer016',
        ),
        migrations.RemoveField(
            model_name='balancemapping',
            name='customer017',
        ),
        migrations.RemoveField(
            model_name='balancemapping',
            name='customer018',
        ),
        migrations.RemoveField(
            model_name='balancemapping',
            name='customer019',
        ),
        migrations.RemoveField(
            model_name='balancemapping',
            name='customer020',
        ),
        migrations.RemoveField(
            model_name='balancemapping',
            name='customer021',
        ),
        migrations.RemoveField(
            model_name='balancemapping',
            name='customer022',
        ),
        migrations.RemoveField(
            model_name='balancemapping',
            name='customer023',
        ),
        migrations.RemoveField(
            model_name='balancemapping',
            name='customer024',
        ),
        migrations.RemoveField(
            model_name='balancemapping',
            name='customer025',
        ),
        migrations.AddField(
            model_name='equipment',
            name='customer001',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段1'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='customer002',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段2'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='customer003',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段3'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='customer004',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段4'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='customer005',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段5'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='customer006',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段6'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='customer007',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段7'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='customer008',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段8'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='customer009',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段9'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='customer010',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段10'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='customer011',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段11'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='customer012',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段12'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='customer013',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段13'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='customer014',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段14'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='customer015',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段15'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='customer016',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段16'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='customer017',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段17'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='customer018',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段18'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='customer019',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段19'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='customer020',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段20'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='customer021',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段21'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='customer022',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段22'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='customer023',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段23'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='customer024',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段24'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='customer025',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义字段25'),
        ),
    ]
