# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-14 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0042_auto_20170314_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipmanage',
            name='status',
            field=models.TextField(choices=[('1', '未分配'), ('2', '已分配'), ('3', '已使用'), ('4', '待回收')], max_length=5, verbose_name='IP状态'),
        ),
    ]
