# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-15 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0043_auto_20170314_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablefieldpropertyclassify',
            name='ordered',
            field=models.IntegerField(default=1, verbose_name='显示顺序'),
        ),
    ]
