# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-15 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0044_tablefieldpropertyclassify_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='monitorploy',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='监控策略'),
        ),
    ]
