# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-16 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0045_equipment_monitorploy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='monitorploy',
        ),
        migrations.AlterField(
            model_name='r_equipment_staff',
            name='createdate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='r_equipment_staff',
            name='createuser',
            field=models.CharField(max_length=100, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='r_equipment_staff',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_staffs', to='cmdb.Equipment', verbose_name='所属设备'),
        ),
        migrations.AlterField(
            model_name='r_equipment_staff',
            name='remark',
            field=models.CharField(max_length=100, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='r_equipment_staff',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.BaseRole', verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='r_equipment_staff',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Staffs', verbose_name='联系人'),
        ),
        migrations.AlterField(
            model_name='r_equipment_staff',
            name='updatedate',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日期'),
        ),
        migrations.AlterField(
            model_name='r_equipment_staff',
            name='updateuser',
            field=models.CharField(max_length=100, verbose_name='更新人'),
        ),
    ]
