# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-16 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0046_auto_20170316_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_provider', to='cmdb.BaseFactory', verbose_name='供应商'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='serviceprovider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_service', to='cmdb.BaseFactory', verbose_name='服务提供商'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='factory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_factory', to='cmdb.BaseFactory', verbose_name='厂商'),
        ),
    ]
