# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-15 09:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=32, verbose_name='昵称')),
                ('avatar', models.CharField(blank=True, max_length=300, null=True, verbose_name='头像')),
                ('cust', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.BaseCustomerInfo', to_field='idcode')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
            ],
            options={
                'verbose_name_plural': '用户',
                'verbose_name': '用户',
            },
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_code', models.CharField(max_length=100)),
                ('menu_name', models.CharField(max_length=200)),
                ('is_avaible', models.IntegerField(default=1)),
            ],
            options={
                'permissions': (('view_menus', 'can view menus'),),
            },
        ),
    ]
