# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-22 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='cust',
        ),
        migrations.AddField(
            model_name='account',
            name='cust_id',
            field=models.CharField(default=1001, max_length=1024, verbose_name='管理客户'),
            preserve_default=False,
        ),
    ]
